# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PodcastDl < Formula
  desc "Download videos from RSS video podcasts"
  homepage "https://github.com/elwin/podcast-tl"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/podcast-dl/releases/download/1.0.1/podcast-dl_1.0.1_Darwin_arm64.tar.gz"
      sha256 "a9a3b21c1dbcc93d39bc33f86907c4112713c992ff72c73905f0c02bba060e6f"

      def install
        bin.install "podcast-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/podcast-dl/releases/download/1.0.1/podcast-dl_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "70d7041372b46ad5fc4a839b8e740e0f64ad0c2d96e469b5667e984d89d6c2b4"

      def install
        bin.install "podcast-dl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/podcast-dl/releases/download/1.0.1/podcast-dl_1.0.1_Linux_arm64.tar.gz"
      sha256 "9aad5f735f6ad2386da4f22c205af5b1a82256eab16afa6061630b3aaa61b3bd"

      def install
        bin.install "podcast-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/podcast-dl/releases/download/1.0.1/podcast-dl_1.0.1_Linux_x86_64.tar.gz"
      sha256 "34387ab02f4db61e056295505c8971f859ab3d226ca37393e6c2dd057d724c01"

      def install
        bin.install "podcast-dl"
      end
    end
  end
end
