# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PodcastDl < Formula
  desc "Download videos from RSS video podcasts"
  homepage "https://github.com/elwin/podcast-tl"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Darwin_arm64.tar.gz"
      sha256 "d18ec8ba7cdff82a261e41235497dd3d75042da9fa861e958f4a9ec54a425c90"

      def install
        bin.install "podcast-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "395e4ced8d5ad8173d2c118d6ecf2f6aa26507a07d687b71b8050b6d0b8f5336"

      def install
        bin.install "podcast-dl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Linux_arm64.tar.gz"
      sha256 "d32b9a00dec0efe8e00166b0b650f7f7b86c379cc811bc87da1a465ba91347d6"

      def install
        bin.install "podcast-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Linux_x86_64.tar.gz"
      sha256 "ff1a11ffcebfb836a991bac6acac9e14ccf82541ec03d1da26df686b2858160d"

      def install
        bin.install "podcast-dl"
      end
    end
  end
end
