# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PodcastDl < Formula
  desc "Download videos from RSS video podcasts"
  homepage "https://github.com/elwin/podcast-tl"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Darwin_arm64.tar.gz"
      sha256 "9a625e9f4c516578df67ab711ff84c207f6bc51ae3aca1f808db40d18b8b6fa3"

      def install
        bin.install "podcast-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "aa2f4ab4bd2cd2e0a42208c48d989e78b3c2af60e18e241c85f7c65284f68c8d"

      def install
        bin.install "podcast-dl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Linux_arm64.tar.gz"
      sha256 "480e5be5d2b92b4fedbf3986b4551064708ace50e05b01a19870673cd77dfbbf"

      def install
        bin.install "podcast-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/podcast-dl/releases/download/v1.0.0/podcast-dl_1.0.0_Linux_x86_64.tar.gz"
      sha256 "82276b79e9d2f6dec74ec671fdb6f63e1ec4c40fa4de93a9d3fd47ffdfdb9e43"

      def install
        bin.install "podcast-dl"
      end
    end
  end
end
