# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Table < Formula
  desc "Print CSV and JSON documents in a table format."
  homepage "https://github.com/elwin/table"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/table/releases/download/v1.0.3/table_1.0.3_Darwin_arm64.tar.gz"
      sha256 "f9237107833b74cb7fc59b266cbb7932d5929f5a279ac3dba286b982d7d61ac6"

      def install
        bin.install "table"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/table/releases/download/v1.0.3/table_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "987e13a55e6c178ad8a815d8f8a2c596578ff76a2e251afdaae4af71ebb30e16"

      def install
        bin.install "table"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/table/releases/download/v1.0.3/table_1.0.3_Linux_arm64.tar.gz"
      sha256 "7e40080c42a16c9d18b6fbefb2e262e0d63cf9006d4e03ac24a108254b36f5b2"

      def install
        bin.install "table"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/table/releases/download/v1.0.3/table_1.0.3_Linux_x86_64.tar.gz"
      sha256 "ff4a5e237fdc0b8d696d008218dc6c27c569d458fc6e2e5153f265640923162d"

      def install
        bin.install "table"
      end
    end
  end
end
