# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toggler < Formula
  desc "Tool to interact with Toggl (currently just rounding)"
  homepage "https://github.com/elwin/toggl"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/toggl/releases/download/v0.0.9/toggler_Darwin_arm64.tar.gz"
      sha256 "1391a96118fd641208b85638f0ba3b1c3f9c7a6406c6d56d8eb194ba07f54d17"

      def install
        bin.install "toggler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/toggl/releases/download/v0.0.9/toggler_Darwin_x86_64.tar.gz"
      sha256 "aefd53fd23c2e6ed6f53bd36e4d46fe1a19f37aa33499ba0a21f4c083aa0cfc1"

      def install
        bin.install "toggler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/toggl/releases/download/v0.0.9/toggler_Linux_arm64.tar.gz"
      sha256 "25107fb644871ef81b1a65fad60032f378dcda91e8f53b81088bb01c55642e7e"

      def install
        bin.install "toggler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/toggl/releases/download/v0.0.9/toggler_Linux_x86_64.tar.gz"
      sha256 "cbadc39b744d2c5000f5a2649e140b0f34c2390c3b2aee6688f9b4fc656972ad"

      def install
        bin.install "toggler"
      end
    end
  end
end
