# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toggler < Formula
  desc "Tool to interact with Toggl (currently just rounding)"
  homepage "https://github.com/elwin/toggl"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/toggl/releases/download/v0.0.7/toggler_Darwin_arm64.tar.gz"
      sha256 "b4b6b5d94c725654b6b2ac92cd5b98cacefc9bd78f320251e89e7880ad62af23"

      def install
        bin.install "toggler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/toggl/releases/download/v0.0.7/toggler_Darwin_x86_64.tar.gz"
      sha256 "7c0f6efd3cd440416871a439704982495d7684486716b70a8273808f2e3ff140"

      def install
        bin.install "toggler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/toggl/releases/download/v0.0.7/toggler_Linux_arm64.tar.gz"
      sha256 "c1713b55e9616e15672693e7d9cfbea750dfafdd5344b75001f44d239d5224f9"

      def install
        bin.install "toggler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/toggl/releases/download/v0.0.7/toggler_Linux_x86_64.tar.gz"
      sha256 "a201eeb9cf009bb48fea99d1b1b3eab309783fdb7dc4b8e48a2414ce751d920e"

      def install
        bin.install "toggler"
      end
    end
  end
end
