# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toggler < Formula
  desc "Tool to interact with Toggl (currently just rounding)"
  homepage "https://github.com/elwin/toggler"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elwin/toggler/releases/download/v0.0.2/toggler_0.0.2_Darwin_arm64.tar.gz"
      sha256 "5d5d7eb92db17311d65014268976ffd61d044915eeeddd94c67b5d3f2424e81f"

      def install
        bin.install "toggler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/toggler/releases/download/v0.0.2/toggler_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "f469e22c0cbc11e29e2be5b3f30591612b8cf0e6e4d023ab3673811d9c70ac72"

      def install
        bin.install "toggler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elwin/toggler/releases/download/v0.0.2/toggler_0.0.2_Linux_arm64.tar.gz"
      sha256 "4bc7b28bd26def11b1539f4fefc6f319c15d7f09f4ef0cec9b7d37a4d877e64f"

      def install
        bin.install "toggler"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elwin/toggler/releases/download/v0.0.2/toggler_0.0.2_Linux_x86_64.tar.gz"
      sha256 "5b9b78594ad331896b8a284d2ea2315748855328c07c910ce2f510ea08dd250c"

      def install
        bin.install "toggler"
      end
    end
  end
end
